### ISSUE TITLE
Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by davidknezic** [axa-ch/style-guide#386]
```
[09:59:59] Starting 'docs-styles'...
(node) warning: possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
  at Gulp.addListener (events.js:179:15)
  at eos (/Users/davidknezic/Repositories/style-guide/node_modules/gulp-watch/node_modules/gulp-batch/node_modules/async-done/node_modules/end-of-stream/index.js:53:9)
  at asyncRunner (/Users/davidknezic/Repositories/style-guide/node_modules/gulp-watch/node_modules/gulp-batch/node_modules/async-done/index.js:43:7)
  at process._tickDomainCallback (node.js:381:11)

(node) warning: possible EventEmitter memory leak detected. 11 finish listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
  at Gulp.addListener (events.js:179:15)
  at eos (/Users/davidknezic/Repositories/style-guide/node_modules/gulp-watch/node_modules/gulp-batch/node_modules/async-done/node_modules/end-of-stream/index.js:54:9)
  at asyncRunner (/Users/davidknezic/Repositories/style-guide/node_modules/gulp-watch/node_modules/gulp-batch/node_modules/async-done/index.js:43:7)
  at process._tickDomainCallback (node.js:381:11)

(node) warning: possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
  at Gulp.addListener (events.js:179:15)
  at eos (/Users/davidknezic/Repositories/style-guide/node_modules/gulp-watch/node_modules/gulp-batch/node_modules/async-done/node_modules/end-of-stream/index.js:56:9)
  at asyncRunner (/Users/davidknezic/Repositories/style-guide/node_modules/gulp-watch/node_modules/gulp-batch/node_modules/async-done/index.js:43:7)
  at process._tickDomainCallback (node.js:381:11)
```

**Comment by AndyOGo** [comment]
same for me:

> (node) warning: possible EventEmitter memory leak detected. 11 task_stop listeners added. Use emitter.setMaxListeners() to increase limit.
> Trace
>     at Gulp.addListener (events.js:252:17)
>     at runSequence (/Users/axawinterthur/dev/style-guide/node_modules/gulp-watch-sequence/node_modules/run-sequence/index.js:94:7)
>     at Timeout.flush [as _onTimeout] (/Users/axawinterthur/dev/style-guide/node_modules/gulp-watch-sequence/index.js:85:19)
>     at tryOnTimeout (timers.js:224:11)
>     at Timer.listOnTimeout (timers.js:198:5)
> (node) warning: possible EventEmitter memory leak detected. 11 task_err listeners added. Use emitter.setMaxListeners() to increase limit.
> Trace
>     at Gulp.addListener (events.js:252:17)
>     at runSequence (/Users/axawinterthur/dev/style-guide/node_modules/gulp-watch-sequence/node_modules/run-sequence/index.js:95:7)
>     at Timeout.flush [as _onTimeout] (/Users/axawinterthur/dev/style-guide/node_modules/gulp-watch-sequence/index.js:85:19)
>     at tryOnTimeout (timers.js:224:11)
>     at Timer.listOnTimeout (timers.js:198:5)

**Comment by AndyOGo** [comment]
a possible [workarround](https://github.com/sun-zheng-an/gulp-shell/issues/23) could be:
```js
require('events').EventEmitter.prototype._maxListeners = 100;
```

**Comment by AndyOGo** [comment]
This Stackoverflow has a similiar problem:
http://stackoverflow.com/questions/29362583/possible-eventemitter-memory-leak-detected-with-gulp-watchify-factor-bundl

**Comment by AndyOGo** [comment]
Well I found some relating issues in gulp-watch and it's choidar dependency:

- https://github.com/floatdrop/gulp-watch/issues/169
- https://github.com/paulmillr/chokidar/issues/297
- https://github.com/paulmillr/chokidar/issues/66

**Comment by AndyOGo** [comment]
Okay I just check our gulp-watch version is completely outdated too -> 1.0.2 VS 4.3.9
