### ISSUE TITLE
Error: pass strings or arrays of strings

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/style-guide#539]
After changing a `jade` file inside docs folder:

> /Users/axawinterthur/dev/style-guide/node_modules/orchestrator/index.js:89
>        					throw new Error('pass strings or arrays of strings');
>        					^
> 
> Error: pass strings or arrays of strings
>     at Gulp.Orchestrator.start (/Users/axawinterthur/dev/style-guide/node_modules/orchestrator/index.js:89:12)
>     at tasks/dev.js:33:26
>     at write (/Users/axawinterthur/dev/style-guide/node_modules/gulp-watch/index.js:144:3)
>     at /Users/axawinterthur/dev/style-guide/node_modules/vinyl-file/index.js:52:4
>     at /Users/axawinterthur/dev/style-guide/node_modules/graceful-fs/graceful-fs.js:78:16
>     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)

**Comment by AndyOGo** [comment]
same issue here https://github.com/floatdrop/gulp-watch/issues/212

**Comment by AndyOGo** [comment]
I check the API of `gulp-watch` and the callback documented [here](https://www.npmjs.com/package/gulp-watch#callback-functionvinyl) does only provide a `vinyl` argument, but no `callback`
