### ISSUE TITLE
Failed to load babel register

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/style-guide#579]
I made a complete reinstall of npm modules with:
```bash
rm -r node_modules/ && npm cache clean && npm install
```

Suddenly my build did not work, turns out `babel-register` is not listed in pur dependency graph.

```bash
[10:57:33] Failed to load external module babel-register
[10:57:33] Failed to load external module babel-core/register
[10:57:33] Failed to load external module babel/register
/Users/axawinterthur/dev/style-guide/gulpfile.babel.js:1
(function (exports, require, module, __filename, __dirname) { import gulp from 'gulp'
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Liftoff.handleArguments (/Users/axawinterthur/dev/style-guide/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/Users/axawinterthur/dev/style-guide/node_modules/liftoff/index.js:198:16)
    at module.exports (/Users/axawinterthur/dev/style-guide/node_modules/flagged-respawn/index.js:17:3)
```

**Comment by davidknezic** [comment]
Awesome!
