### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/style-guide#585]
npm install correctly installs `babel-register` but gulp can't find it.

From the logs at docker hub:

> +-- babel-register@6.14.0 
> ...
> > gulp build
> 
> [08:39:47] Failed to load external module babel-register
> [08:39:47] Failed to load external module babel-core/register
> [08:39:47] Failed to load external module babel/register
> [91m/usr/src/app/gulpfile.babel.js:1
> (function (exports, require, module, __filename, __dirname) { import gulp from 'gulp'
> [0m[91m                                                              ^^^^^^
> 
> [0m[91mSyntaxError: Unexpected token import
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:387:25)
>     at Object.Module._extensions..js (module.js:422:10)
>     at Module.load (module.js:357:32)
>     at Function.Module._load (module.js:314:12)
>     at Module.require (module.js:367:17)
>     at require (internal/module.js:20:19)
>     at Liftoff.handleArguments (/usr/src/app/node_modules/gulp/bin/gulp.js:116:3)
>     at Liftoff.<anonymous> (/usr/src/app/node_modules/liftoff/index.js:198:16)
>     at module.exports (/usr/src/app/node_modules/flagged-respawn/index.js:17:3)
> [0m[91m
> [0m[91mnpm [0m[91minfo [0m[91mlifecycle @axa-ch/style-guide@0.15.0~build: Failed to exec build script

## How to reproduce locally
run:
```bash
rm -r node_modules/ && npm cache clean && npm install && npm run build
```

## Related issues
https://github.com/yeoman/generator-webapp/issues/356

**Comment by AndyOGo** [comment]
btw this warning seems important:

> npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

**Comment by AndyOGo** [comment]
I found installing `babel-register` again manually after `npm install` (which has it in it's `package.json` file) workarounds the issue.
