### ISSUE TITLE
Production build errors after mighty webpack upgrade

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/style-guide#614]
see: https://hub.docker.com/r/axacom/web-style-guide/builds/bdegbddxmqjbawie9igiynx/

## LESS

https://github.com/webpack/extract-text-webpack-plugin/issues/50

> ERROR in ./less/style.less
> Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
> Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
>     at Object.module.exports.pitch (/usr/src/app/node_modules/extract-text-webpack-plugin/loader.js:21:9)
>     at applySyncOrAsync (/usr/src/app/node_modules/happypack/lib/applyLoaders.js:341:21)
>     at applyPitchLoader (/usr/src/app/node_modules/happypack/lib/applyLoaders.js:201:7)
>     at applyPitchLoaders (/usr/src/app/node_modules/happypack/lib/applyLoaders.js:222:4)
>     at applyLoaders (/usr/src/app/node_modules/happypack/lib/applyLoaders.js:116:3)
>     at HappyWorker.compile (/usr/src/app/node_modules/happypack/lib/HappyWorker.js:32:3)
>     at process.accept (/usr/src/app/node_modules/happypack/lib/HappyWorkerChannel.js:24:14)
>     at emitTwo (events.js:100:13)
>     at process.emit (events.js:185:7)
>     at handleMessage (internal/child_process.js:718:10)
>     at /usr/src/app/node_modules/happypack/lib/HappyLoader.js:46:23
>     at Object.Thread::css:0:1 (/usr/src/app/node_modules/happypack/lib/HappyPlugin.js:321:7)
>     at ChildProcess.acceptMessageFromWorker (/usr/src/app/node_modules/happypack/lib/HappyThread.js:66:32)
>     at emitTwo (events.js:105:20)
>     at ChildProcess.emit (events.js:185:7)
>     at handleMessage (internal/child_process.js:718:10)
>     at Pipe.channel.onread (internal/child_process.js:444:11)
>  @ ./js/index-with-styles.js 3:0-29[39m[22m
> 
> [1m[31mERROR in ./docs/less/docs.less
> Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
> Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
>     at Object.module.exports.pitch (/usr/src/app/node_modules/extract-text-webpack-plugin/loader.js:21:9)
>     at applySyncOrAsync (/usr/src/app/node_modules/happypack/lib/applyLoaders.js:341:21)
>     at applyPitchLoader (/usr/src/app/node_modules/happypack/lib/applyLoaders.js:201:7)
>     at applyPitchLoaders (/usr/src/app/node_modules/happypack/lib/applyLoaders.js:222:4)
>     at applyLoaders (/usr/src/app/node_modules/happypack/lib/applyLoaders.js:116:3)
>     at HappyWorker.compile (/usr/src/app/node_modules/happypack/lib/HappyWorker.js:32:3)
>     at process.accept (/usr/src/app/node_modules/happypack/lib/HappyWorkerChannel.js:24:14)
>     at emitTwo (events.js:100:13)
>     at process.emit (events.js:185:7)
>     at handleMessage (internal/child_process.js:718:10)
>     at /usr/src/app/node_modules/happypack/lib/HappyLoader.js:46:23
>     at Object.Thread::css:1:1 (/usr/src/app/node_modules/happypack/lib/HappyPlugin.js:321:7)
>     at ChildProcess.acceptMessageFromWorker (/usr/src/app/node_modules/happypack/lib/HappyThread.js:66:32)
>     at emitTwo (events.js:105:20)
>     at ChildProcess.emit (events.js:185:7)
>     at handleMessage (internal/child_process.js:718:10)
>     at Pipe.channel.onread (internal/child_process.js:444:11)
>  @ ./docs/js/index-with-styles.js 3:0-28[39m[22m

## Git revision sync

> Error: [git-rev-sync] no git repository found
> [docs]     at _getGitDirectory (/usr/src/app/node_modules/git-rev-sync/index.js:46:11)
> [docs]     at _getGitDirectory (/usr/src/app/node_modules/git-rev-sync/index.js:57:10)
> [docs]     at _getGitDirectory (/usr/src/app/node_modules/git-rev-sync/index.js:57:10)
> [docs]     at _getGitDirectory (/usr/src/app/node_modules/git-rev-sync/index.js:57:10)
> [docs]     at _getGitDirectory (/usr/src/app/node_modules/git-rev-sync/index.js:57:10)
> [docs]     at _getGitDirectory (/usr/src/app/node_modules/git-rev-sync/index.js:57:10)
> [docs]     at branch (/usr/src/app/node_modules/git-rev-sync/index.js:61:16)
> [docs]     at Object.long (/usr/src/app/node_modules/git-rev-sync/index.js:74:11)
> [docs]     at Object.<anonymous> (/usr/src/app/lib/build-docs.js:83:20)
> [docs]     at Module._compile (module.js:413:34)
> [docs]     at loader (/usr/src/app/node_modules/babel-register/lib/node.js:146:5)
> [docs]     at Object.require.extensions.(anonymous function) [as .js] (/usr/src/app/node_modules/babel-register/lib/node.js:156:7)
> [docs]     at Module.load (module.js:357:32)
> [docs]     at Function.Module._load (module.js:314:12)
> [docs]     at Function.Module.runMain (module.js:447:10)
> [docs]     at /usr/src/app/node_modules/babel-cli/lib/_babel-node.js:151:24

**Comment by AndyOGo** [comment]
Happypack seems to be involved, I think I setup the wrong way to work properly with `extract-text-webpack-plugin`

https://github.com/amireh/happypack/issues/12
https://github.com/amireh/happypack/issues/14#issuecomment-208254692

**Comment by AndyOGo** [comment]
> [all:watch] [less:watch] /Users/axawinterthur/dev/style-guide/node_modules/configstore/index.js:86
> [all:watch] [less:watch] 	return this.all[key];
> [all:watch] [less:watch] 	               ^
> [all:watch] [less:watch]
> [all:watch] [less:watch] TypeError: Cannot read property 'optOut' of undefined
> [all:watch] [less:watch]     at Object.Configstore.get (/Users/axawinterthur/dev/style-guide/node_modules/configstore/index.js:86:17)
> [all:watch] [less:watch]     at UpdateNotifier.check (/Users/axawinterthur/dev/style-guide/node_modules/update-notifier/index.js:47:18)
> [all:watch] [less:watch]     at module.exports (/Users/axawinterthur/dev/style-guide/node_modules/update-notifier/index.js:127:17)
> [all:watch] [less:watch]     at Object.<anonymous> (/Users/axawinterthur/dev/style-guide/node_modules/sync-files/bin/sync-files.js:121:3)
> [all:watch] [less:watch]     at Module._compile (module.js:413:34)
> [all:watch] [less:watch]     at Object.Module._extensions..js (module.js:422:10)
> [all:watch] [less:watch]     at Module.load (module.js:357:32)
> [all:watch] [less:watch]     at Function.Module._load (module.js:314:12)
> [all:watch] [less:watch]     at Function.Module.runMain (module.js:447:10)
> [all:watch] [less:watch]     at startup (node.js:146:18)
> [all:watch] [less:watch]
