### ISSUE TITLE
Module build failed: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/style-guide#635]
````sh
ERROR in ./docs/scss/docs.scss
Module build failed: ReferenceError: window is not defined
    at /Users/axawinterthur/dev/style-guide/node_modules/happypack/loader.js?id=production-sass!/Users/axawinterthur/dev/style-guide/docs/scss/docs.scss:157:31
    at /Users/axawinterthur/dev/style-guide/node_modules/happypack/loader.js?id=production-sass!/Users/axawinterthur/dev/style-guide/docs/scss/docs.scss:152:48
    at module.exports (/Users/axawinterthur/dev/style-guide/node_modules/happypack/loader.js?id=production-sass!/Users/axawinterthur/dev/style-guide/docs/scss/docs.scss:174:69)
    at Object.<anonymous> (/Users/axawinterthur/dev/style-guide/node_modules/happypack/loader.js?id=production-sass!/Users/axawinterthur/dev/style-guide/docs/scss/docs.scss:54:37)
    at __webpack_require__ (/Users/axawinterthur/dev/style-guide/node_modules/happypack/loader.js?id=production-sass!/Users/axawinterthur/dev/style-guide/docs/scss/docs.scss:21:30)
    at /Users/axawinterthur/dev/style-guide/node_modules/happypack/loader.js?id=production-sass!/Users/axawinterthur/dev/style-guide/docs/scss/docs.scss:41:18
    at Object.<anonymous> (/Users/axawinterthur/dev/style-guide/node_modules/happypack/loader.js?id=production-sass!/Users/axawinterthur/dev/style-guide/docs/scss/docs.scss:44:10)
    at Module._compile (module.js:413:34)
    at Object.loaderContext.exec (/Users/axawinterthur/dev/style-guide/node_modules/webpack-core/lib/NormalModuleMixin.js:88:7)
    at Object.<anonymous> (/Users/axawinterthur/dev/style-guide/node_modules/extract-text-webpack-plugin/loader.js:97:22)
    at Compiler.<anonymous> (/Users/axawinterthur/dev/style-guide/node_modules/webpack/lib/Compiler.js:214:10)
    at /Users/axawinterthur/dev/style-guide/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (/Users/axawinterthur/dev/style-guide/node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (/Users/axawinterthur/dev/style-guide/node_modules/extract-text-webpack-plugin/loader.js:78:5)
    at Compiler.next (/Users/axawinterthur/dev/style-guide/node_modules/tapable/lib/Tapable.js:69:14)
    at Compiler.<anonymous> (/Users/axawinterthur/dev/style-guide/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (/Users/axawinterthur/dev/style-guide/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.<anonymous> (/Users/axawinterthur/dev/style-guide/node_modules/webpack/lib/Compiler.js:400:9)
    at Compilation.<anonymous> (/Users/axawinterthur/dev/style-guide/node_modules/webpack/lib/Compilation.js:577:13)
    at Compilation.applyPluginsAsync (/Users/axawinterthur/dev/style-guide/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/axawinterthur/dev/style-guide/node_modules/webpack/lib/Compilation.js:572:10)
    at Compilation.applyPluginsAsync (/Users/axawinterthur/dev/style-guide/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/axawinterthur/dev/style-guide/node_modules/webpack/lib/Compilation.js:567:9)
    at Compilation.applyPluginsAsync (/Users/axawinterthur/dev/style-guide/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/axawinterthur/dev/style-guide/node_modules/webpack/lib/Compilation.js:563:8)
    at Compilation.applyPluginsAsync (/Users/axawinterthur/dev/style-guide/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.seal (/Users/axawinterthur/dev/style-guide/node_modules/webpack/lib/Compilation.js:525:7)
    at Compiler.<anonymous> (/Users/axawinterthur/dev/style-guide/node_modules/webpack/lib/Compiler.js:397:15)
    at /Users/axawinterthur/dev/style-guide/node_modules/tapable/lib/Tapable.js:103:11
    at Compilation.<anonymous> (/Users/axawinterthur/dev/style-guide/node_modules/webpack/lib/Compilation.js:445:10)
 @ ./docs/js/index-with-styles.js 3:0-28
````

**Comment by AndyOGo** [comment]
http://stackoverflow.com/questions/28223040/window-not-defined-error-when-using-extract-text-webpack-plugin-react

**Comment by AndyOGo** [comment]
I quickly disabled happypack for css
